export const stringsPT = {
  appName: 'Ei-Ebook',
  welcome: 'Bem-vindo ao Ei-Ebook',
  createAccount: 'Crie sua conta',
  enterAccount: 'Entre na sua conta',
  enter: 'Entrar',
  signUp: 'Criar conta',
  email: 'Seu email',
  emailSmall: 'Seu email está inválido',
  password: 'Sua senha',
  passwordSmall: 'Sua senha precisa ter pelo menos 8 caracteres',
  cookiesWarning:
    'Utilizamos cookies para armazenar configurações e preferências.',
  learnMore: 'Saiba mais.',
  contact: 'Contato',
  ptBR: 'Português (Brasil)',
  en: 'Inglês',
  notFound: 'Você não deveria estar nessa rota, oxe...',
  backHome: 'Voltar',
  signUpWarning: 'Ao cadastrar-se você estará concordando com nossos',
  terms: 'Termos de Serviços.',
  name: 'Seu nome',
  ok: 'Ok',
  nameSmall: 'Seu nome está muito curto',
  wait: 'Aguarde...',
  oopss: 'Oopss...',
  internalError: 'Erro interno',
  emailAlreadyExists: 'Email já está em uso',
  userNotFound: 'Usuário não encontrado! Crie uma conta',
};
