export const stringsEN = {
  appName: 'Ei-Ebook',
  welcome: 'Welcome to Ei-Ebook',
  createAccount: 'Create your account',
  enterAccount: 'Login to your account',
  enter: 'Login',
  signUp: 'Sign up',
  email: 'Your email',
  emailSmall: 'Your email is invalid',
  password: 'Your password',
  passwordSmall: 'Your password must be at least 8 characters',
  cookiesWarning: 'We use cookies to store settings and preferences.',
  learnMore: 'Learn more.',
  contact: 'Contact',
  ptBR: 'Portuguese (Brazil)',
  en: 'English',
  notFound: "You shouldn't be on this route, oxe...",
  backHome: 'Back',
  signUpWarning: 'By registering you are agreeing to our',
  terms: 'Terms of Service.',
  name: 'Your name',
  nameSmall: 'Your name is too short',
  ok: 'Ok',
  oopss: 'Oopss...',
  emailAlreadyExists: 'Email is already in use',
  internalError: 'Internal error',
  wait: 'Wait a moment...',
  userNotFound: 'User not found! Create an account',
  profileWarning: 'Select an image for your profile',
};
